import { useState, useEffect } from 'react';
import { api } from '../../lib/api';
import { Calendar, Loader2, Clock, MapPin, CheckCircle2 } from 'lucide-react';

export default function Timetable() {
  const [timetable, setTimetable] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  useEffect(() => {
    fetchMyTimetable();
  }, []);

  const fetchMyTimetable = async () => {
    try {
      setLoading(true);
      const res = await api.get('/teacher/timetable');
      if (res.timetable) {
        setTimetable(res.timetable);
      }
    } catch (err) {
      console.error(err);
      setError('Failed to load your timetable.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="space-y-6 animate-in fade-in duration-500">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-slate-900 flex items-center gap-2">
            <Calendar className="text-indigo-600" /> My Timetable
          </h1>
          <p className="text-sm text-slate-500 mt-1">
            Your personalized weekly schedule, auto-generated by SomoBloom AI.
          </p>
        </div>
      </div>

      {error && (
        <div className="bg-red-50 text-red-600 p-4 rounded-lg text-sm font-medium">
          {error}
        </div>
      )}

      <div className="bg-white border border-slate-200 rounded-xl p-6 shadow-sm min-h-[500px]">
        {loading ? (
          <div className="flex flex-col items-center justify-center h-full text-slate-400 py-20">
            <Loader2 size={32} className="animate-spin mb-4" />
            <p>Loading your schedule...</p>
          </div>
        ) : timetable && timetable.schedule && timetable.schedule.length > 0 ? (
          <div className="space-y-8">
            {timetable.schedule.map((dayObj, i) => (
              <div key={i} className="animate-in slide-in-from-bottom-2 fade-in" style={{ animationDelay: `${i * 100}ms` }}>
                <h3 className="text-lg font-bold text-slate-800 mb-4 pb-2 border-b border-slate-100 flex items-center gap-2">
                  <Clock size={18} className="text-indigo-500" />
                  {dayObj.day}
                </h3>
                
                <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">
                  {dayObj.slots && dayObj.slots.map((slot, j) => (
                    <div key={j} className="relative overflow-hidden bg-gradient-to-br from-indigo-50 to-white border border-indigo-100 rounded-xl p-4 shadow-sm hover:shadow-md transition-all hover:-translate-y-1 group">
                      <div className="absolute top-0 right-0 w-16 h-16 bg-indigo-500/5 rounded-bl-full -mr-8 -mt-8 transition-transform group-hover:scale-150" />
                      
                      <div className="flex justify-between items-start mb-3 relative z-10">
                        <span className="text-xs font-black text-indigo-700 bg-white border border-indigo-100 px-2.5 py-1 rounded-md shadow-sm flex items-center gap-1.5">
                          <Clock size={12} /> {slot.time}
                        </span>
                        <CheckCircle2 size={16} className="text-emerald-500 opacity-0 group-hover:opacity-100 transition-opacity" />
                      </div>
                      
                      <div className="relative z-10">
                        <h4 className="font-extrabold text-slate-900 text-lg mb-1">{slot.subject}</h4>
                        <div className="flex items-center gap-1.5 text-sm font-semibold text-slate-600 bg-slate-100/80 w-fit px-2.5 py-1 rounded-md">
                          <MapPin size={14} className="text-slate-400" /> {slot.class}
                        </div>
                      </div>
                    </div>
                  ))}
                  
                  {(!dayObj.slots || dayObj.slots.length === 0) && (
                    <div className="col-span-full text-center text-sm text-slate-400 py-6 bg-slate-50 rounded-xl border border-dashed border-slate-200">
                      No classes scheduled for this day
                    </div>
                  )}
                </div>
              </div>
            ))}
          </div>
        ) : (
          <div className="flex flex-col items-center justify-center h-full text-slate-400 text-center py-20">
            <div className="w-20 h-20 bg-slate-50 rounded-full flex items-center justify-center mb-4 border border-slate-100">
              <Calendar size={32} className="text-slate-300" />
            </div>
            <p className="text-lg font-bold text-slate-700 mb-1">No Schedule Found</p>
            <p className="text-sm max-w-sm text-slate-500">
              You haven't been assigned any classes in the current master timetable. Please contact the administrator if this is an error.
            </p>
          </div>
        )}
      </div>
    </div>
  );
}
