import React from 'react';

export default function ReportCardPrintView({ student, portfolio, competencies, attendance }) {
  if (!student) return null;

  return (
    <div className="print-only" style={{ display: 'none', padding: 40, fontFamily: 'serif', color: 'black' }}>
      <style>
        {`
          @media print {
            body * {
              visibility: hidden;
            }
            .print-only, .print-only * {
              visibility: visible;
            }
            .print-only {
              display: block !important;
              position: absolute;
              left: 0;
              top: 0;
              width: 100%;
              background: white !important;
              padding: 20px;
            }
            .no-print {
              display: none !important;
            }
            @page { size: A4; margin: 1cm; }
          }
        `}
      </style>
      
      <div style={{ textAlign: 'center', marginBottom: 30, borderBottom: '2px solid black', paddingBottom: 20 }}>
        <h1 style={{ margin: 0, fontSize: 32, letterSpacing: 2 }}>SOMOBLOOM ACADEMY</h1>
        <h2 style={{ margin: '10px 0', fontSize: 24, fontWeight: 'normal' }}>CBC Official Report Card</h2>
        <p style={{ margin: 0, fontSize: 16 }}>Term 2, 2026</p>
      </div>

      <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 30, padding: 15, border: '1px solid #ccc' }}>
        <div>
          <p><strong>Student Name:</strong> {student.name}</p>
          <p><strong>Admission No:</strong> {student.id}</p>
          <p><strong>Grade/Class:</strong> {student.grade}</p>
        </div>
        <div style={{ textAlign: 'right' }}>
          <p><strong>Attendance:</strong> {attendance?.percentage || 'N/A'}%</p>
          <p><strong>Interests:</strong> {student.interests || 'N/A'}</p>
        </div>
      </div>

      <div style={{ marginBottom: 30 }}>
        <h3 style={{ borderBottom: '1px solid black', paddingBottom: 5 }}>Core Competencies</h3>
        <table style={{ width: '100%', borderCollapse: 'collapse', marginTop: 10 }}>
          <thead>
            <tr>
              <th style={{ border: '1px solid black', padding: 8, textAlign: 'left', width: '70%' }}>Competency Area</th>
              <th style={{ border: '1px solid black', padding: 8, textAlign: 'center', width: '30%' }}>Performance Level</th>
            </tr>
          </thead>
          <tbody>
            {competencies?.map((c, i) => (
              <tr key={i}>
                <td style={{ border: '1px solid black', padding: 8 }}>{c.subject}</td>
                <td style={{ border: '1px solid black', padding: 8, textAlign: 'center' }}>
                  {c.score >= 4 ? 'Exceeding Expectations' : 
                   c.score >= 3 ? 'Meeting Expectations' : 
                   c.score >= 2 ? 'Approaching Expectations' : 'Below Expectations'}
                </td>
              </tr>
            ))}
            {(!competencies || competencies.length === 0) && (
              <tr>
                <td colSpan={2} style={{ border: '1px solid black', padding: 8, textAlign: 'center' }}>No competencies assessed yet.</td>
              </tr>
            )}
          </tbody>
        </table>
      </div>

      <div style={{ marginBottom: 30 }}>
        <h3 style={{ borderBottom: '1px solid black', paddingBottom: 5 }}>Portfolio Highlights</h3>
        <ul style={{ paddingLeft: 20 }}>
          {portfolio?.map((item, i) => (
            <li key={i} style={{ marginBottom: 10 }}>
              <strong>{item.title}</strong> ({item.subject}) - {item.date}
            </li>
          ))}
          {(!portfolio || portfolio.length === 0) && (
            <li>No portfolio items submitted for this term.</li>
          )}
        </ul>
      </div>

      <div style={{ marginTop: 50, display: 'flex', justifyContent: 'space-between', paddingTop: 20 }}>
        <div style={{ width: '40%', textAlign: 'center', borderTop: '1px solid black', paddingTop: 10 }}>
          <strong>Class Teacher's Signature</strong>
        </div>
        <div style={{ width: '40%', textAlign: 'center', borderTop: '1px solid black', paddingTop: 10 }}>
          <strong>Head Teacher's Signature</strong>
        </div>
      </div>
      
      <div style={{ marginTop: 40, textAlign: 'center', fontSize: 12, color: 'gray' }}>
        Generated by SomoBloom Portal on {new Date().toLocaleDateString()}
      </div>
    </div>
  );
}
